name: conversationbot

on: workflow_dispatch

jobs:
  connect_with_bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        run: |
          echo 'Gajraj123'
          echo $GITHUB_WORKSPACE
