name: dbopsexp
on: 
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: write
jobs: 
  dbops-download:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0 # Let's get all the branches    
        - name: OS level modifications.
          run: |
            make changepermission
            make installneofetch

        - name: Log python version
          env:
            STUDENT_NAME: Sonal Mehta
          run: ./test-shell.plugin
