name: parameterexp
on: 
  workflow_dispatch:
      inputs:
            logLevel:
              description: 'Log level'
              required: true
              default: 'warning'
              type: choice
              options:
              - info
              - warning
              - debug
            tags:
              description: 'Test scenario tags'
              required: false
              type: boolean
            environment:
              description: 'Environment to run tests against'
              type: environment
              required: true
jobs: 
  parameter-way:
    runs-on: ubuntu-latest
    steps:
      - name: Log python version
        run: |
          python --version
      - name: Parameter information    
        run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"