name: Start the execution

on: 
  repository_dispatch:
    types: [build]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: javascript base actions
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Mantra Mehta'
      - name: display output from javascript based actions
        run: echo "${{ steps.greet.outputs.time }}"
      - name: echo a string
        run: echo 'Gajraj'
      - name: execute multiple line command
        run: |
          node -v
          npm -v
          cat /etc/*-release
      - name: execute make file command
        run: |
          make listdir
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
