name: Start the execution

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: echo a string
        run: echo 'Gajraj'
      - name: execute multiple line command
        run: |
          node -v
          npm -v
          cat /etc/*-release
      - name: execute make file command
        run: |
          make sample1
          make sample2
